FROM golang:1.21-alpine

WORKDIR /app

# 安裝基本工具
RUN apk add --no-cache git gcc musl-dev

# 複製 go.mod 和 go.sum
COPY go.mod go.sum ./

# 下載依賴
RUN go mod download

# 複製源代碼
COPY . .

# 設置環境變數
ENV GO111MODULE=on \
    CGO_ENABLED=1 \
    GOOS=linux \
    GOARCH=amd64

# 編譯並運行應用程式
CMD ["go", "run", "cmd/main.go"] 