version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=gochat
      - DB_PASSWORD=gochat123
      - DB_NAME=gochat
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis

  mysql:
    image: mariadb:10.11
    ports:
      - "3333:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=gochat
      - MYSQL_USER=gochat
      - MYSQL_PASSWORD=gochat123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:6.2
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: 