apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: replicas-patch.yaml
  - path: resource-patch.yaml

configMapGenerator:
  - name: gochat-config
    behavior: merge
    literals:
      - APP_ENV=production
      - DB_HOST=mariadb
      - DB_PORT=3306
      - REDIS_HOST=redis.prod 