apiVersion: apps/v1
kind: Deployment
metadata:
  name: gochat
spec:
  template:
    spec:
      containers:
      - name: gochat
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m" 