apiVersion: apps/v1
kind: Deployment
metadata:
  name: gochat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gochat
  template:
    metadata:
      labels:
        app: gochat
    spec:
      containers:
      - name: gochat
        image: gcr.io/marine-embassy-455211-m1/gochat:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: gochat-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: gochat-config
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: gochat-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gochat-secrets
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: gochat-config
              key: DB_NAME
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: gochat-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: gochat-config
              key: REDIS_PORT
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10 