apiVersion: v1
kind: Secret
metadata:
  name: gochat-secrets
type: Opaque
data:
  DB_USER: Z29jaGF0  # base64 encoded "gochat"
  DB_PASSWORD: Z29jaGF0MTIz  # base64 encoded "gochat123"
  APP_SECRET: eW91cl9zZWN1cmVfYXBwX3NlY3JldA==  # base64 encoded "your_secure_app_secret"
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk  # base64 encoded "rootpassword" 