apiVersion: v1
kind: Service
metadata:
  name: gochat
  labels:
    app: gochat
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8099
      protocol: TCP
  selector:
    app: gochat 